# Generated by Django 5.2.7 on 2026-01-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_alter_message_options_message_read_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="caller_offer",
            field=models.TextField(
                blank=True, help_text="SDP offer from caller", null=True
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="ice_candidates",
            field=models.TextField(
                blank=True, help_text="JSON array of ICE candidates", null=True
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="receiver_answer",
            field=models.TextField(
                blank=True, help_text="SDP answer from receiver", null=True
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("ringing", "Ringing"),
                    ("active", "Active"),
                    ("ongoing", "Ongoing"),
                    ("ended", "Ended"),
                    ("missed", "Missed"),
                    ("declined", "Declined"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
    ]
