# Generated by Django 5.2.7 on 2025-11-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("NURSE", "Nurse"),
                    ("DOCTOR", "Doctor"),
                    ("EXPERT", "Expert"),
                    ("PATIENT", "Patient"),
                ],
                default="NURSE",
                help_text="User role in the medical system",
                max_length=10,
            ),
        ),
    ]
