# Generated by Django 5.2.7 on 2025-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the knowledge document", max_length=255
                    ),
                ),
                ("content", models.TextField(help_text="Full content of the document")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("GUIDELINE", "Clinical Guideline"),
                            ("PROTOCOL", "Medical Protocol"),
                            ("RESEARCH", "Research Paper"),
                            ("MANUAL", "Medical Manual"),
                            ("CASE_STUDY", "Case Study"),
                            ("DRUG_INFO", "Drug Information"),
                            ("PROCEDURE", "Medical Procedure"),
                            ("REFERENCE", "Reference Material"),
                            ("TRAINING", "Training Material"),
                            ("OTHER", "Other"),
                        ],
                        default="REFERENCE",
                        help_text="Type/category of the document",
                        max_length=15,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source or origin of the document (journal, organization, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author(s) of the document",
                        max_length=255,
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True,
                        help_text="Original publication date of the document",
                        null=True,
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the document was uploaded to the system",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the document is currently active and available for use",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for easier searching",
                        max_length=500,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version number of the document",
                        max_length=20,
                    ),
                ),
                (
                    "last_reviewed",
                    models.DateField(
                        blank=True,
                        help_text="Date when the document was last reviewed for accuracy",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Knowledge Document",
                "verbose_name_plural": "Knowledge Documents",
                "ordering": ["-upload_date"],
            },
        ),
    ]
