# Generated by Django 5.2.7 on 2025-10-08 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded this document",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["document_type", "is_active"],
                name="knowledge_k_documen_6cf0df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["title"], name="knowledge_k_title_d14b87_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["upload_date"], name="knowledge_k_upload__5781fd_idx"
            ),
        ),
    ]
