# Generated by Django 5.2.7 on 2025-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(help_text="Patient symptoms and chief complaints"),
                ),
                (
                    "vital_signs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Patient vital signs (temperature, blood pressure, heart rate, etc.)",
                    ),
                ),
                (
                    "ai_diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated diagnosis and recommendations",
                    ),
                ),
                (
                    "doctor_diagnosis",
                    models.TextField(
                        blank=True,
                        help_text="Doctor's final diagnosis and treatment plan",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DOCTOR_REVIEW", "Doctor Review"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the diagnostic case",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Priority"),
                            ("MEDIUM", "Medium Priority"),
                            ("HIGH", "High Priority"),
                            ("URGENT", "Urgent"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        help_text="Priority level of the case",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the case was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the case was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostic Case",
                "verbose_name_plural": "Diagnostic Cases",
                "ordering": ["-created_at"],
            },
        ),
    ]
