# Generated by Django 5.2.7 on 2025-10-08 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnoses", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor assigned to review the case",
                limit_choices_to={"role": "DOCTOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="nurse",
            field=models.ForeignKey(
                help_text="Nurse who initiated the case",
                limit_choices_to={"role": "NURSE"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nurse_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient associated with this diagnostic case",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="patients.patient",
            ),
        ),
    ]
