# Generated by Django 5.2.7 on 2025-10-08 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="doctor_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "Approved"),
                    ("modified", "Modified"),
                    ("rejected", "Rejected"),
                ],
                help_text="Doctor's decision on AI diagnosis",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="doctor_modifications",
            field=models.TextField(
                blank=True, help_text="JSON data for modifications made by doctor"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="doctor_rejection",
            field=models.TextField(
                blank=True, help_text="JSON data for AI diagnosis rejection details"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="doctor_review",
            field=models.TextField(
                blank=True, help_text="Doctor's review notes and decision"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="final_diagnosis",
            field=models.TextField(
                blank=True, help_text="Final diagnosis after doctor review"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when the case was reviewed", null=True
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor who reviewed this case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
