# Generated by Django 5.2.7 on 2025-11-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoses", "0004_patient_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="treatment_comments",
            field=models.TextField(
                blank=True,
                help_text="Doctor's comments and observations on treatment plan",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="treatment_comments_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when treatment comments were added",
                null=True,
            ),
        ),
    ]
