# Generated by Django 5.2.7 on 2025-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoses", "0005_case_treatment_comments_case_treatment_comments_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="symptom_image",
            field=models.ImageField(
                blank=True,
                help_text="Visual documentation of symptoms (e.g., rash, injury, wound)",
                null=True,
                upload_to="case_symptom_images/%Y/%m/%d/",
            ),
        ),
    ]
