# Generated by Django 5.2.7 on 2025-11-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoses", "0006_case_symptom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="symptom_image_filename",
            field=models.CharField(
                blank=True,
                help_text="Original filename of the symptom image",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="symptom_image",
            field=models.TextField(
                blank=True,
                help_text="Visual documentation of symptoms (base64 encoded image)",
                null=True,
            ),
        ),
    ]
