# Generated by Django 5.2.7 on 2025-11-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnoses", "0007_case_symptom_image_filename_alter_case_symptom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="diagnosis_comments",
            field=models.TextField(
                blank=True,
                help_text="Doctor's comments and observations on AI diagnosis",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="diagnosis_comments_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when diagnosis comments were added",
                null=True,
            ),
        ),
    ]
