# Generated by Django 5.2.7 on 2025-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateTimeField(
                        help_text="Date and time of the medical visit"
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        help_text="Patient symptoms reported during the visit"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, help_text="Medical diagnosis made during the visit"
                    ),
                ),
                (
                    "treatment",
                    models.TextField(
                        blank=True,
                        help_text="Treatment plan and medications prescribed",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes and observations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Patient first name", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Patient last name", max_length=100),
                ),
                ("date_of_birth", models.DateField(help_text="Patient date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("P", "Prefer not to say"),
                        ],
                        help_text="Patient gender",
                        max_length=1,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Patient contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Patient residential address"
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Patient medical history and past conditions",
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True, help_text="Known allergies and adverse reactions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
