# Generated by Django 5.2.7 on 2025-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(
                db_index=True, help_text="Patient first name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(
                db_index=True, help_text="Patient last name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Patient contact phone number",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="patients_pa_last_na_1b32a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["phone_number"], name="patients_pa_phone_n_933975_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["created_at"], name="patients_pa_created_542792_idx"
            ),
        ),
    ]
