# Generated by Django 5.2.7 on 2025-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_patient_user_alter_patient_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(
                blank=True,
                help_text="Patient medical history and past conditions (free text)",
            ),
        ),
    ]
